/*
 * A Blog System
 *
 * send, manage and share your blog 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type Blog struct {

	BlogID string `json:"BlogID,omitempty"`

	AuthorID string `json:"AuthorID,omitempty"`

	AuthorName string `json:"AuthorName,omitempty"`

	CreateTime float32 `json:"CreateTime,omitempty"`

	Title string `json:"Title,omitempty"`

	Abstract string `json:"Abstract,omitempty"`

	Content string `json:"Content,omitempty"`
}
