/*
 * A Blog System
 *
 * send, manage and share your blog 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package server

type Comment struct {

	// The ID of the Blog
	BlogId string `json:"BlogId,omitempty"`

	// The name of the one who comments
	OwnName string `json:"ownName,omitempty"`

	// The time of the comment
	CommentTime float32 `json:"commentTime,omitempty"`

	// The content of the comment
	Content string `json:"content,omitempty"`
}
