/*
 * A Blog System
 *
 * send, manage and share your blog 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package server

type Tag struct {

	// The ID of the Blog
	BlogID string `json:"BlogID,omitempty"`

	// all of the tags
	Content string `json:"content,omitempty"`
}
